# Generated by Django 4.0.4 on 2022-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='todo',
            field=models.TextField(default=1, verbose_name='To Do'),
            preserve_default=False,
        ),
    ]
