# Generated by Django 4.0.4 on 2022-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_assignment_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Assignment Name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='todo',
            field=models.TextField(max_length=250, verbose_name='To Do'),
        ),
    ]
